### ISSUE TITLE
What is the default password for coreos

### ISSUE THREAD

**Issue by JackChen255** [coreos/update-ssh-keys#9]
I installed the latest coreos_production_iso_image.iso to create a virtual machine. The IP is automatically generated. But how can I SSH login to this IP? If user is core and password is core or empty, I can't login. And it requires old password if I want to run passwd to reset the password. Could anyone tell me the password for core and root?
Also, "systemctl stop firewalld" fails because it requires "Interactive authentication required".

**Comment by JackChen255** [comment]
@philips I have ran ssh-keygen in the coreos and didn't type anything for prepurchase. But now I still can't SSH to this coreos from another machine. Because it always asks for a password.
[root@localhost ~]# ssh -l core 172.24.17.177
core@172.24.17.177's password:
Permission denied, please try again.

**Comment by JackChen255** [comment]
@crawford Can you help on it? I have follow this post to run ssh-keygen
https://coreos.com/os/docs/latest/booting-with-qemu.html

**Comment by mischief** [comment]
@JackChen255 to set a password, you can set the kernel commandline paramter `coreos.autologin=` to get a shell on the console. from there, you can run `sudo passwd core` to set the core user's password.

however, it is recommended that you use ssh keys instead.

if you find a problem with coreos, please file an issue on the [bugs](https://github.com/coreos/bugs/issues) repo.

**Comment by JackChen255** [comment]
OK. Thanks. I use passwd to change root password.
